name: Update Charlie's Twitter

on:
  schedule:
    - cron: '0 * * * *' # Run every hour
  workflow_dispatch:

jobs:
  update_repos:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Call index.js
      run: 
        touch .env
        echo REPLICATE_API_TOKEN=$REPLICATE_API_TOKEN >> .env
        echo TWITTER_CONSUMER_KEY=$TWITTER_CONSUMER_KEY >> .env
        echo TWITTER_CONSUMER_SECRET=$TWITTER_CONSUMER_SECRET >> .env
        echo TWITTER_ACCESS_TOKEN_KEY=$TWITTER_ACCESS_TOKEN_KEY >> .env
        echo TWITTER_ACCESS_TOKEN_SECRET=$TWITTER_ACCESS_TOKEN_SECRET >> .env
        npm run start
      env:
        REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        TWITTER_ACCESS_TOKEN_KEY: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET}}
